### ISSUE TITLE
Rename MaybeError to something better

### ISSUE THREAD

**Issue by Marwes** [Marwes/gluon#104]
[MaybeError](https://github.com/Marwes/gluon/blob/0987a3a3d11d8ff6f61f7160541311dbe8b86278/vm/src/api.rs#L775) is used to represent results for functions which may 'panic' (in the context of gluon not Rust). `MaybeError` is a really terrible name for this however so renaming it is a good idea.

Possible names:

```rust
enum Panicking<T, E> { }
enum Panic<T, E> { }
enum Diverging<T, E> { }
// More?
```

Let the bikeshedding comence!

**Comment by leshow** [comment]
Maybe something like

```
enum OkOrPanic<T, E> { }
enum PanicResult<T, E> { }
```

It's more of an XOR than an Or I guess, but I think it gets the point across. Since MaybeError can one of two values it's closer to an Either than a Maybe though isn't it?

**Comment by Marwes** [comment]
`PanicResult` mimics `Result` which seems good. The only reason `Result` is not used for panicking is because it is already mapped to gluon's `Result` type.

`OkOrPanic` may be descriptive but `Result` is not called `OkOrError` so I am less keen on that option.

**Comment by brendanzab** [comment]
`RuntimeResult`?

What about renaming `Err` to `Diverge` or `Panic`? Might be clearer in the context of the runtime.

**Comment by brendanzab** [comment]
Wondering if we should also add `#[must_use]` to it (despite my misgivings about that attribute in general).

**Comment by Marwes** [comment]
+1 on renaming `Err` to `Panic` (diverge is perhaps a bit more obscure and has additional meaning)

**Comment by Marwes** [comment]
> Wondering if we should also add #[must_use] to it (despite my misgivings about that attribute in general).

Might be a good idea. I'd expect users to only produce the value however, the only actual consumer is [Pushable](https://github.com/Marwes/gluon/blob/0987a3a3d11d8ff6f61f7160541311dbe8b86278/vm/src/api.rs#L786) which converts it into `Status` and `Status` needs to be used to provide an API which is compatible with C (its not currently 100% compatible but `Status` ensures that it can be without to much work).

What do you dislike about `#[must_use]`?

**Comment by brendanzab** [comment]
I think it might reduce the potential bugs, so it would be nice to have it.

> What do you dislike about `#[must_use]`?

It feels a bit hacky/inconsistent... I would kind of prefer require all values to be explicitly ignored, but I understand that that is probably quite a bit of a pain syntactically (that was tried out before in Rust's history).

**Comment by Marwes** [comment]
Perhaps `RuntimeResult` is a bit better than `PanicResult` which can be read as "the result of a panic" when in reality panicking is just one option.

```rust
pub enum RuntimeResult<T, E> {
    Ok(T),
    Panic(E),
}
```

**Comment by brendanzab** [comment]
What about:

```rust
pub enum RuntimeResult<T, E> {
    Return(T),
    Panic(E),
}
```

**Comment by Marwes** [comment]
I don't have any strong feelings either way about `Ok` or `Return` either is fine for me.
