### ISSUE TITLE
Version 0.1.3 is broken by Rust 1.12 (type inference with AsRef)

### ISSUE THREAD

**Issue by bluss** [Marwes/gluon#164]
See https://internals.rust-lang.org/t/regression-report-stable-2016-08-16-vs-beta-2016-09-21/4119

Since this is fixed in git, only needs new release.

**Comment by Marwes** [comment]
I am already aware of this but thanks for reporting. Probably going to release a major version bump (0.2.0) this weekend.

**Comment by Marwes** [comment]
Fixed with 0.2.0 being released.
