### ISSUE TITLE
Add more precise locations to type errors

### ISSUE THREAD

**Issue by Marwes** [Marwes/gluon#20]
Currently the location of a type error is reported as being in the same place as the expression it occured in. This location can be rather misleading in many common cases.

Type errors in function calls should be reported at the argument rather than the call.
```
Current:
map 1 Nil
^~~~~~~~
Better version:
map 1 Nil
    ^
```

Type errors in patterns should be reported at the patterns (or expressions) location rather than the enclosing expression
```
Expression:
let { x, y } = 1 in ...
Current:
let { x, y } = 1 in ...
^~~~~~~~~~~~~~~~~
Better version:
let { x, y } = 1 in ...
    ^~~~~~~~
```

**Comment by Marwes** [comment]
Better spans for errors in function calls were implemented in 14c692aa59dfca7114e611a739383c69f6ae8603

**Comment by beneills** [comment]
This issue is fixed:

```
>>let {x, y} = 7 in x
<top>:Line: 1, Column: 5: Expected the following types to be equal
Expected: Int
Found: { x: 669, y: 670 }
1 errors were found during unification:
Types do not match:
	Expected: Int
	Found: { x: 669, y: 670 }
let {x, y} = 7 in x
    ^~~~~
```

**Comment by Marwes** [comment]
Seems I had fixed both of these cases. There are still some problems with inexact locations though that is logged under #8 instead.

Thanks for reporting this!
