### ISSUE TITLE
Add an environment variable which specifies directories to look for imported files

### ISSUE THREAD

**Issue by Marwes** [Marwes/gluon#23]
The import.rs module would should be extended to look for an environment variable (maybe `GLUON_PATH`?) and use that for import lookup as well.

**Comment by leshow** [comment]
I'd like to contribute something to your project, this issue seems easy enough. Do you have a particular way you might like to see this implemented?

I'm a beginner at Rust, so please let me know if this is way off base

https://github.com/leshow/gluon/blob/master/src/import.rs#L104

**Comment by bjz** [comment]
Thanks for the interest!

I'm wondering if it would be possible to pass the path down from a higher level - ie. closer to the entrypoint. That way we can push the global state out to the edge of the code, making things more testable. Just an idea!

**Comment by bjz** [comment]
Feel free to open a WIP PR, referencing this issue - that way we can talk over there.

**Comment by Marwes** [comment]
I think it may be, as @bjz says that the addition of GLUON_PATH should be a bit higher up to keep the creation of an `Import` pure. I am thinking that it could be added in [new_vm](https://github.com/Marwes/gluon/blob/9058c253c23358cdfc249e88c5789bd3b4f6e98c/src/lib.rs#L543-L555) which serves to create a vm initialized with a sane set of defaults.

Also see https://github.com/Marwes/gluon/blob/9058c253c23358cdfc249e88c5789bd3b4f6e98c/tests/vm.rs#L39-L42 for how to retrieve and add a new path.

**Comment by leshow** [comment]
awesome! I'll make some changes and open a PR

**Comment by Marwes** [comment]
Closed by #79

**Comment by brendanzab** [comment]
@leshow In the future, if you put 'Closes #N' of 'Fixes #N' in the PR description, the corresponding issue will be auto-closed. :)
