### ISSUE TITLE
Add F#/OCaml/Elm-style piping operators

### ISSUE THREAD

**Issue by bjz** [Marwes/gluon#34]
This seems to be what all the cool kids are doing! It is also much easier for people to understand vs Haskell's `(.)` and `($)`:

```rust
/// Backward function application, where `f <| x == f x`
let (<|) f x : a -> (a -> b) -> b = f x

/// Forward function application, where `x |> f == f x`
let (|>) x f : (a -> b) -> a -> b = f x

/// Function composition, where `f >> g == (\x -> f (g x))`
let (>>) f g : (a -> b) -> (b -> c) -> a -> c = \x -> f (g x)

/// Function composition, where `f << g == (\x -> g (f x))`
let (<<) f g : (b -> c) -> (a -> b) -> a -> c = \x -> g (f x)
```

Seeing as we are thinking in higher kinds, I wonder if we could define these in terms of `Applicative` and `Category`?

**Comment by bjz** [comment]
One question though is with respect to operator precedence. The ergonomics of these `(|>)` only works if it binds _really_ loosely. Here is are the precedences as defined in the [Elm source](https://github.com/elm-lang/core/blob/4.0.3/src/Basics.elm#L501-L567):

```elm
infixr 9 <<
infixl 9 >>
infixr 0 <|
infixl 0 |>
```

This allows you to do nice stuff like:

```elm
ngon 5 30
  |> filled blue
  |> move (10,10)
  |> scale 2
```

**Comment by Marwes** [comment]
I definitely want this. The only reason I haven't added them so far is because the current handling of operator precedence is poor. Currently the parser just has precedence of some [predefined operators](https://github.com/Marwes/gluon/blob/76f6bf049fd93e663a2a9e7dba6e49bc358b857f/parser/src/lib.rs#L123-L139). It is probably fine to add these operators to the table as well to make it possible to use them now but I think tackling precedence properly should be of relatively high priority.

**Comment by Marwes** [comment]
Related #3

**Comment by bjz** [comment]
What should we do about the monadic `(>>)`? I would definitely favor using it for function composition - seems like a more common use case.

**Comment by Marwes** [comment]
Function is probably more common than monads though it may depend a bit on how pervasive monads end up being.

**Comment by Marwes** [comment]
The only reason not to do this is probably to save people used to Haskell some pain as `>>` is equivalent to the applicative operator `*>`. Probably `>>` is only there for backwards compatibility reasons as I believe `Monad` was a part of `Haskell` before `Applicative` (and then there is the whole issue of `Applicative` not being a superclass of `Monad` though that is fixed now changed).

**Comment by bjz** [comment]
Yeah - it would be nice to just have `(*>)`... I'm actually starting to understand Haskell more that I'm figuring out that many of these functions are just more specific instances of more general versions.

**Comment by Boiethios** [comment]
I tried to use it (in "Try Gluon" -> "linked_list"), I changed the fold-left line with:

```gluon
foldl f <| f a y <| ys
```

But I am getting:

```
error: Undefined variable `<|`
```

**Comment by Marwes** [comment]
`<|` isn't in the prelude so you need to import it manually

```f#
let { (<|) } = import! std.function
```

I have been considering adding this and some more conveniences to the prelude however.

http://gluon-lang.org/doc/nightly/std/prelude.html
http://gluon-lang.org/doc/nightly/std/function.html
