### ISSUE TITLE
Update rustyline when Windows support appears on crates.io

### ISSUE THREAD

**Issue by brendanzab** [Marwes/gluon#39]
As discussed in https://github.com/Marwes/gluon/pull/35#issuecomment-233140511:

> I started some work to replace the [linenoise](https://github.com/octplane/rust-linenoise/) dependency with [rustyline](https://github.com/kkawakam/rustyline). There shouldn't be any problems porting over any changes since it is mostly a rust implementation of linenoise but it also has a better completion api which should make it possible to add tab-completion in the REPL!

**Comment by bjz** [comment]
Might also be nice to keep the history between sessions. What do you think?

**Comment by Marwes** [comment]
That is a good idea and it is supported by both libraries. The only question may be where to store it. Probably in .dotfiles on linux and AppData on Windows? I think I have seen a crate which handled this but I can't remember what it is called

**Comment by bjz** [comment]
Yeah - that's why I held off on doing with linenoise. :/

**Comment by Marwes** [comment]
Merged rustyline support in #45 though I will leave this open until the Windows support is more complete.

**Comment by bjz** [comment]
Should we rename the issue to be clearer?

**Comment by Marwes** [comment]
Updated the title.

**Comment by Marwes** [comment]
Closed by #128
