### ISSUE TITLE
Implement Applicative and Functor for State and Writer

### ISSUE THREAD

**Issue by bjz** [Marwes/gluon#43]
I reckon it would be nice to make `Monad` inherit from `Applicative`, and to remove `return` in favor of `pure`. In order to do that however, we need to implement the missing interfaces for the `State` and `Writer` types.

**Comment by bjz** [comment]
Does this look reasonable?

```ocaml
let functor : Functor (State s) =
    let map f m : (a -> b) -> State s a -> State s b =
        \state ->
            let { value, state } = m state
            { value = f value, state = state  }

    { map }

let applicative : Applicative (State s) =
    let (<*>) mf state : State s (a -> b) -> State s a -> State s b =
        let { value, state } = mf state
        functor.map value state

    let pure value: a -> State s a =
        \state -> { value, state }

    { (<*>), pure }

let monad: Monad (State s) =
    let (>>=) m f: State s a -> (a -> State s b) -> State s b =
        \state -> (functor.map f m) state

    { (>>=), return = applicative.pure }
```

**Comment by Marwes** [comment]
Looks good to me, assuming the types match. Should be good to remove `return` as well though I am not sure how to best deal with inheritance.

Option 1: Keep `return`/`pure` in the `Monad` type.
```
type Monad m = {
    (>>=) : m a -> (a -> m b) -> m b,
    pure: a -> m a
}
```
Option 2: Remove `return`/`pure` in the `Monad` type but add it to the result of `make_Monad`.
```
type Monad m = {
    (>>=) : m a -> (a -> m b) -> m b,
    pure: a -> m a
}

let make_Monad applicative m =
    let { (>>=) } = m
    let (>>) l r = l >>= \_ -> r
    let forM_ xs f =
        match xs with
            | Cons y ys ->
                f y >> forM_ ys f
            | Nil -> return ()
    {
        (>>=),
        return = return,
        (>>),
        join = \mm -> mm >>= id,
        map = \x f -> x >>= (\y -> return (f x)),
        lift2 = \f lm rm -> lm >>= \l -> rm >>= \r -> f l r,
        forM_,
       pure = applicative.pure
    }
```

Option 2: Remove `return`/`pure` in the `Monad` type but and add `Applicative` as a field.
```
type Monad m = {
    (>>=) : m a -> (a -> m b) -> m b,
    applicative: Applicative m
}
```

This is only mentioning a few options (which work with the current type system, a better type system might have a canonical way of handling this).

**Comment by bjz** [comment]
Yep - was thinking of going with Option 2.

**Comment by bjz** [comment]
By the way, what is `lift2`? Is that just `map2`, but constrained to monads?

**Comment by bjz** [comment]
Also, `forM_` is a bonkers name!

**Comment by Marwes** [comment]
> By the way, what is lift2? Is that just map2, but constrained to monads?
I think so. When in doubt just assume I copied Haskell though it seems I actually got the name "wrong"
http://hackage.haskell.org/package/base-4.9.0.0/docs/Control-Monad.html#v:liftM2

> Also, forM_ is a bonkers name!
Yeah, pretty much. Haskell has the convention that monadic combinators ending with `_` ignore the result so it is at least consistent.

**Comment by Marwes** [comment]
Option 2 is good, it is a bit unfortunate that it makes the raw `Monad` type a bit less useful but that may be dealt with in the future (possible with some extension to the type system)
