### ISSUE TITLE
Only use the (->) operator for function type constructors

### ISSUE THREAD

**Issue by bjz** [Marwes/gluon#57]
At the moment the Gluon's syntax overloads the `(->)` operator for three things:

- as a function type constructor
- to separate arguments from the body in lambdas
- to separate the pattern from the body match arms

It would be nice to use `(=>)` for the latter two cases to disambiguate this, and to leave us open to unifying the type and value syntaxes in the future.

For example:

```diff
 type Functor f = {
     map : (a -> b) -> f a -> f b
 }
 
 let functor_Option : Functor Option = {
-    map = \f x ->
-        match x with
-            | Some y -> Some (f y)
-            | None -> None
+    map = \f x =>
+        match x with
+            | Some y => Some (f y)
+            | None => None
 }
```

**Comment by bjz** [comment]
I'm actually wondering how necessary this is... also, maybe we would want another operator for kind-level functions. Looking around the literature, in TaPL and the 1ML paper for example, it seems like folks use `(=>)` for functions from kind to kind. Not sure what the reasoning is. Idris just uses `(->)` for both.

**Comment by Marwes** [comment]
The 1ML paper used `=>` for impure functions and `->` for pure thats not relevant now but it might be worth considering.

The current use of `->` is mimicking ML languages so it may be worth keeping for that reason alone (Rust uses `=>` though)

**Comment by bjz** [comment]
`(->)` feels lighter in general too, which is a mark in its favor.

**Comment by bjz** [comment]
I'm going to close this for now, we can always discuss this further at a later date.
