### ISSUE TITLE
Consider using a chat service for community discussion

### ISSUE THREAD

**Issue by bjz** [Marwes/gluon#63]
Would be nice to have some kind of place for free-form, asynchronous discussions that don't really fit into github issues. Perhaps Gitter? http://gitter.im/ - we could put a badge to it on the README.

**Comment by theblacksquid** [comment]
I was about to suggest a public slack chat or IRC, but following the link, it actually looks really built around GH, nice.

**Comment by bjz** [comment]
Something that has travis support as well would also be great. They use it for https://github.com/diesel-rs/diesel - not sure how it has gone with them.

**Comment by bjz** [comment]
Slack would be cool - there's more friction for users signing up though, and you can't see the scrollback if you're not signed in.

**Comment by Marwes** [comment]
I setup a gitter room for now. I can see about setting up github and travis integration with it as well in a bit. Let me know if anything else I should setup (or if another service seems better).

https://gitter.im/Marwes/gluon

**Comment by Marwes** [comment]
PR #65

**Comment by Marwes** [comment]
Are there any particular benefits to Slack? I hear about it a lot but I have never actually used it.

**Comment by bjz** [comment]
We use it at work and for my personal game project. It's a better fit for private teams, but people seem to try to use it for everything. It doesn't really have a sidebar for integrations though - you really need a separate room for it to spam away at things.

**Comment by bjz** [comment]
I think this is done! Gitter seems reasonable for now. https://gitter.im/Marwes/gluon <- for folks who missed it!
