### ISSUE TITLE
Add row polymorphism (aka. extensible records) to type system

### ISSUE THREAD

**Issue by brendanzab** [Marwes/gluon#92]
This could be useful for adding a more powerful effect system, or perhaps for adding default implementations for interfaces/traits/modules/typeclasses (whatever we call them?).

## Resources

Feel free to add more if you like!

- [willtim/row-polymorphism](https://github.com/willtim/row-polymorphism) - Example row-polymorphism implementations 
- [Extensible records with scoped labels](https://www.microsoft.com/en-us/research/publication/extensible-records-with-scoped-labels/)
- [Koka: Programming with Row Polymorphic Effect Types](https://www.microsoft.com/en-us/research/publication/koka-programming-with-row-polymorphic-effect-types-2/)
- [Elm: Records](http://elm-lang.org/docs/records)
- [Elm: Simplified Records](http://elm-lang.org/blog/compilers-as-assistants#simplified-records)
- [PureScript: Handling Native Effects with the Eff Monad](http://www.purescript.org/learn/eff/)
- [PureScript Language Guide: Kind System](https://github.com/purescript/purescript/wiki/Language-Guide#kind-system) 
- [PureScript Language Guide: Kinds](https://github.com/purescript/purescript/wiki/Language-Guide#kinds)

**Comment by Marwes** [comment]
Just adding a some thoughts about implementation details.

Currently records are represented in vm as a flat array of values which ensures very fast access but in return this means that `{ x : Int, y : String } != { y : String, x : Int }`. With a row polymorphic type the representation of `{ x : Int, y : String | r }` would presumably be some kind of hashmap or tree (or `x` and `y` field could be laid out first on memory with the rest of fields to follow, but that is probably to restrictive).

Possibly the representation of non-polymorphic records could still be stored as compactly as they are now but could be enhanced with a `Map<Field, FieldOffset>` to retrieve fields when it is accessed in polymorphic context?

Alternatively storing them as hashmaps always is possible, dynamic languages seem to do alright with that representation.

Should `{ x : Int, y : String }` unify with `{ y : String, x : Int }` to produce `{ x : Int, y : String | r }`? (Might be subtyping problems?)
