### ISSUE TITLE
Use a non-cryptographic hasher for HashMaps

### ISSUE THREAD

**Issue by brendanzab** [Marwes/gluon#95]
We have a bunch of `HashMap`s scattered all around the codebase, all of which use the default cryptographic `SipHasher`. We should switch to using a non-cryptographic hasher, for example [fnv](https://crates.io/crates/fnv).

**Comment by Marwes** [comment]
`BTreeMap` may be an alternative as well.

**Comment by brendanzab** [comment]
I know that rustc uses FNV internally... not sure what would be best - might depend on the use case.

**Comment by leshow** [comment]
I have a branch with hashmap replaced with a hashmap using fnv, I will submit a PR, let me know if it's what you're looking for.

I added a type alias to `base::src::types`

```
pub type HashMapFnv<K, V> = HashMap<K, V, BuildHasherDefault<FnvHasher>>;
```

and replaced calls to `HashMap` with `HashMapFnv`, along with cleaning up the imports. It compiles fine, just about to test.

**Comment by brendanzab** [comment]
Not sure if `types` is the right place - that's more where the 'AST for Gluon's types' goes. Where did you find those maps being used?

Maybe `FnvMap` might be more succint? That's what rustc calls it.

**Comment by leshow** [comment]
The hashmaps were being used all over

```
	modified:   base/src/fixed.rs
	modified:   base/src/instantiate.rs
	modified:   base/src/lib.rs
	modified:   base/src/scoped_map.rs
	modified:   base/src/symbol.rs
	modified:   base/src/types.rs
	modified:   check/src/rename.rs
	modified:   check/src/unify.rs
	modified:   src/import.rs
	modified:   vm/src/gc.rs
	modified:   vm/src/interner.rs
	modified:   vm/src/macros.rs
	modified:   vm/src/thread.rs
	modified:   vm/src/types.rs
	modified:   vm/src/value.rs
	modified:   vm/src/vm.rs
```

almost all of these changes are removing `std::colllections::HashMap` and renaming though and changing the instantiation call
