### ISSUE TITLE
Rewrite the macro system

### ISSUE THREAD

**Issue by Marwes** [Marwes/gluon#99]
The current macro system is quite limited and the only macro which currently exist is `import`. Even just for that macro the current implementation is inadequate. Thus a rewrite (or even removal with `import` moved to be known at the language level).

### Issues with import

* Does not handle cyclic imports anymore (not that hard to fix but might as well be done in the rewrite)

* An imported module will be loaded and executed even if the module importing it fails typechecking. This behavior may actually be fine but I think it is worth mentioning, the alternative is to only typecheck all modules before loading and executing them.

* Buggy when multiple threads try to load modules simultaneously

* Cannot support parallel loading (from a single thread) of modules if that is desired

### Sketch

If the macro system is rewritten this is my current sketch for the idea.

```rust
pub trait Macro: ::mopa::Any + Send + Sync {
    fn expand(&self,
              /// `&mut MacroExpander` to allow macros to store state between calls
              env: &mut MacroExpander,
              arguments: &mut [ast::LExpr<TcIdent>])
              -> Result<ast::LExpr<TcIdent>, Error>;
    fn clone(&self) -> Box<Macro>;
}

pub struct MacroExpander<'a> {
    pub env: &'a Thread,
    pub macros: &'a MacroEnv,
    /// Allow macros to be defined locally so that they can be overridden temporarily
    pub local_macros: HashMap<String, Box<Macro>>,
    errors: Errors<Error>,
    /// Some sort of generic state storage to let each macro store some state
}
```
With something like this it should (at least) support the `import` macro since by using the same `MacroExpander` for resolving all recursive imports the `import` macro can store the names of each recursively imported module to resolve cyclic references.

**Comment by Marwes** [comment]
I will add more to the issue as I come up with or encounter problems with it.

**Comment by brendanzab** [comment]
Does import being a macro mean that we are recompiling lots of code (like the C preprocessor?)

**Comment by Marwes** [comment]
Nope. It first checks if the module has already been compiled an reuses it if it exists

**Comment by brendanzab** [comment]
Ah, cool.
